-- Auditoría Pendientes - Supabase schema
-- Run this file in Supabase SQL Editor after creating your project.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text not null default 'Usuario',
  role text not null default 'Auditor' check (role in ('Administrador', 'Supervisor', 'Auditor')),
  status text not null default 'Activo' check (status in ('Activo', 'Inactivo')),
  last_access_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incidents (
  id text primary key,
  created_at timestamptz not null default now(),
  hotel text not null,
  department text not null,
  responsible_area text,
  incident_type text not null,
  impact text,
  priority text not null default 'Media' check (priority in ('Baja', 'Media', 'Alta', 'Crítica')),
  status text not null default 'Pendiente' check (status in ('Pendiente', 'En proceso', 'En espera de respuesta', 'Escalado', 'Resuelto', 'Cerrado')),
  responsible text,
  assigned_to uuid references auth.users(id),
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  assigned_at timestamptz,
  due_at date,
  actual_due_at date,
  description text not null,
  root_cause text,
  action_taken text,
  close_reason text,
  evidence_url text,
  final_comment text,
  closed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  incident_id text references public.incidents(id) on delete set null,
  occurred_at timestamptz not null default now(),
  user_id uuid references auth.users(id),
  action text not null,
  changed_field text,
  old_value text,
  new_value text,
  comment text,
  hotel text,
  status text
);

create table if not exists public.catalogs (
  id bigint generated by default as identity primary key,
  category text not null,
  value text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists catalogs_category_value_uidx
  on public.catalogs (lower(category), lower(value));

create index if not exists incidents_status_idx on public.incidents(status);
create index if not exists incidents_priority_idx on public.incidents(priority);
create index if not exists incidents_due_at_idx on public.incidents(due_at);
create index if not exists incidents_created_by_idx on public.incidents(created_by);
create index if not exists incidents_assigned_to_idx on public.incidents(assigned_to);
create index if not exists audit_log_incident_id_idx on public.audit_log(incident_id);
create index if not exists audit_log_occurred_at_idx on public.audit_log(occurred_at desc);

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.role
  from public.profiles p
  where p.id = (select auth.uid())
    and p.status = 'Activo'
  limit 1
$$;

revoke all on function public.current_app_role() from public;
grant execute on function public.current_app_role() to authenticated;

alter table public.profiles enable row level security;
alter table public.incidents enable row level security;
alter table public.audit_log enable row level security;
alter table public.catalogs enable row level security;

drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
on public.profiles
for select
to authenticated
using (
  id = (select auth.uid())
  or public.current_app_role() in ('Administrador', 'Supervisor')
);

drop policy if exists "profiles_insert_self_auditor" on public.profiles;
create policy "profiles_insert_self_auditor"
on public.profiles
for insert
to authenticated
with check (
  id = (select auth.uid())
  and role = 'Auditor'
  and status = 'Activo'
);

drop policy if exists "profiles_update_admin_or_self" on public.profiles;
create policy "profiles_update_admin_or_self"
on public.profiles
for update
to authenticated
using (
  public.current_app_role() = 'Administrador'
  or id = (select auth.uid())
)
with check (
  public.current_app_role() = 'Administrador'
  or (
    id = (select auth.uid())
    and role = 'Auditor'
    and status = 'Activo'
  )
);

drop policy if exists "incidents_select_authenticated" on public.incidents;
create policy "incidents_select_authenticated"
on public.incidents
for select
to authenticated
using (public.current_app_role() in ('Administrador', 'Supervisor', 'Auditor'));

drop policy if exists "incidents_insert_authenticated" on public.incidents;
create policy "incidents_insert_authenticated"
on public.incidents
for insert
to authenticated
with check (
  created_by = (select auth.uid())
  and public.current_app_role() in ('Administrador', 'Supervisor', 'Auditor')
);

drop policy if exists "incidents_update_by_role_or_owner" on public.incidents;
create policy "incidents_update_by_role_or_owner"
on public.incidents
for update
to authenticated
using (
  public.current_app_role() in ('Administrador', 'Supervisor')
  or created_by = (select auth.uid())
  or assigned_to = (select auth.uid())
)
with check (
  public.current_app_role() in ('Administrador', 'Supervisor')
  or created_by = (select auth.uid())
  or assigned_to = (select auth.uid())
);

drop policy if exists "incidents_delete_admin" on public.incidents;
create policy "incidents_delete_admin"
on public.incidents
for delete
to authenticated
using (public.current_app_role() = 'Administrador');

drop policy if exists "audit_select_authenticated" on public.audit_log;
create policy "audit_select_authenticated"
on public.audit_log
for select
to authenticated
using (public.current_app_role() in ('Administrador', 'Supervisor', 'Auditor'));

drop policy if exists "audit_insert_authenticated" on public.audit_log;
create policy "audit_insert_authenticated"
on public.audit_log
for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and public.current_app_role() in ('Administrador', 'Supervisor', 'Auditor')
);

drop policy if exists "catalogs_select_authenticated" on public.catalogs;
create policy "catalogs_select_authenticated"
on public.catalogs
for select
to authenticated
using (public.current_app_role() in ('Administrador', 'Supervisor', 'Auditor'));

drop policy if exists "catalogs_manage_admin_supervisor" on public.catalogs;
create policy "catalogs_manage_admin_supervisor"
on public.catalogs
for all
to authenticated
using (public.current_app_role() in ('Administrador', 'Supervisor'))
with check (public.current_app_role() in ('Administrador', 'Supervisor'));

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.incidents to authenticated;
grant select, insert on public.audit_log to authenticated;
grant select, insert, update, delete on public.catalogs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into public.catalogs (category, value) values
  ('Hotel', '5910 - PPRL'),
  ('Hotel', '5911 - ZEL'),
  ('Hotel', '5917 - MPCB'),
  ('Hotel', '5918 - MCB'),
  ('Hotel', '5930 - PGC'),
  ('Departamento', 'Recepción'),
  ('Departamento', 'Reservas'),
  ('Departamento', 'A&B'),
  ('Departamento', 'Spa'),
  ('Departamento', 'Contabilidad'),
  ('Departamento', 'IT'),
  ('Departamento', 'Club Meliá'),
  ('Departamento', 'Auditoría Nocturna'),
  ('Departamento', 'Auditoría Diurna'),
  ('Área Responsable', 'Operaciones'),
  ('Área Responsable', 'Finanzas'),
  ('Área Responsable', 'Contabilidad'),
  ('Área Responsable', 'Revenue'),
  ('Área Responsable', 'Sistemas'),
  ('Área Responsable', 'Auditoría'),
  ('Tipo de Incidencia', 'Cobro no realizado'),
  ('Tipo de Incidencia', 'Routing incorrecto'),
  ('Tipo de Incidencia', 'Check-in mal procesado'),
  ('Tipo de Incidencia', 'Rate Code incorrecto'),
  ('Tipo de Incidencia', 'Factura no volcada a SAP'),
  ('Tipo de Incidencia', 'Diferencia POS vs PMS'),
  ('Tipo de Incidencia', 'Resort Credit incorrecto'),
  ('Tipo de Incidencia', 'HTC incorrecto'),
  ('Tipo de Incidencia', 'Falta de soporte'),
  ('Tipo de Incidencia', 'Incidencia IT'),
  ('Impacto', 'Operativo'),
  ('Impacto', 'Financiero'),
  ('Impacto', 'Contable'),
  ('Impacto', 'Cliente'),
  ('Impacto', 'Sistema'),
  ('Prioridad', 'Baja'),
  ('Prioridad', 'Media'),
  ('Prioridad', 'Alta'),
  ('Prioridad', 'Crítica'),
  ('Estatus', 'Pendiente'),
  ('Estatus', 'En proceso'),
  ('Estatus', 'En espera de respuesta'),
  ('Estatus', 'Escalado'),
  ('Estatus', 'Resuelto'),
  ('Estatus', 'Cerrado'),
  ('Causa raíz', 'Error operativo'),
  ('Causa raíz', 'Falta de soporte'),
  ('Causa raíz', 'Configuración incorrecta'),
  ('Causa raíz', 'Proceso incompleto'),
  ('Causa raíz', 'Incidencia de sistema'),
  ('Acción tomada', 'Corrección en PMS'),
  ('Acción tomada', 'Corrección contable'),
  ('Acción tomada', 'Escalamiento a IT'),
  ('Acción tomada', 'Capacitación al equipo'),
  ('Acción tomada', 'Validación documental')
on conflict do nothing;

-- Bootstrap admin:
-- 1. Create the first user in Supabase Auth.
-- 2. Copy that user's UUID.
-- 3. Run:
-- insert into public.profiles (id, email, display_name, role, status)
-- values ('USER_UUID_HERE', 'admin@example.com', 'Administrador', 'Administrador', 'Activo')
-- on conflict (id) do update set role = 'Administrador', status = 'Activo';
